on: [push, pull_request]
name: Linux

jobs:

  build:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        perl: [ '5.36', '5.30', '5.26', '5.16' ]
    name: Perl ${{ matrix.perl }}
    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: switch to perl ${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: run tests
        env:
          PERL_USE_UNSAFE_INC: 0
        run: |
            perl -v
            cpanm ExtUtils::MakeMaker Test::Pod Test::Pod::Coverage || cat /home/runner/.cpanm/work/*/build.log
            perl -Mparent -e0 || cpanm parent
            rm -rf /home/runner/.cpanm/work/*
            cpanm --installdeps . || cat /home/runner/.cpanm/work/*/build.log
            perl Makefile.PL
            make test TEST_VERBOSE=1
